# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    resource_class: medium

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1024m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies


      - run: ./gradlew dependencies

      # run tests!
      - run: ./gradlew clean testClasses

      # run tests!
      - run: ./gradlew  test

      - store_test_results:
          path: build/test-results
